### ISSUE TITLE
"An exception Index Out of Range" & "GUI" error is generated when the user follows the steps mentioned in the "https://github.com/alttester/AltTester-Unity-SDK/issues/1112"

### ISSUE THREAD

**Issue by Umer457** [alttester/AltTester-Unity-SDK#1123] opened 2023-02-16 11:28 UTC
**Description:** "Index Out of Range" & "GUI" error is generated when the user follows the steps mentioned in the "https://github.com/alttester/AltTester-Unity-SDK/issues/1112"

**Steps to Reproduce:**
1) Open Unity Hub and Create a new Unity Project"
2) Import the Alt Tester package after downloading from the website
3) After importing an error is generated: "Assets/AltTester/AltServer/AltMockUpPointerInputModule.cs(5,19): error CS0234"
4) Follow the steps as mentioned in the URL: https://github.com/alttester/AltTester-Unity-SDK/issues/1112
5) Then Return to Unity, the user sees that the "Alt Tester" appears in the top menu
6) Click on the Alt Tester Option and then in the sub menu  Click on "AltTester Editor"

**Expected Behaviour:** The solution should work:

**Actual Behaviour:** "Index Out of Range" & "GUI" error is generated 

Attaching the a video reference

https://user-images.githubusercontent.com/68316446/219352530-514ae382-1751-41b3-b96c-51c10fc698a6.mov

**AltTester Version:** 1.8.2
**Device:** MacBook Pro (13-inch, M1, 2020)
**OS:** Montery

**Comment by sandraaltom** [comment] 2023-06-06 10:23
@MihaiCuc98 or @iulianatodoran Could you check if you can reproduce it?

**Comment by iulianatodoran** [comment] 2023-09-22 05:52
The issue is not reproducible anymore with the **AltTester Unity SDK v `2.0.2`** as the workaround mentioned in https://github.com/alttester/AltTester-Unity-SDK/issues/1112 is not necessary anymore and the error described in Step 3 not being triggered anymore (the issue was fixed in a newer version of the SDK)

**Considering that, I will close this issue.**

**Closed by iulianatodoran** 2023-09-22 05:52 UTC
