### ISSUE TITLE
altwebsocket-sharp is not linked to the driver nuget package

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1192] opened 2023-03-30 06:08 UTC
## Steps to reproduce
 
1. Create a nunit project
2. Add AltDriver package inside it
3. Instantiate an AltDriver
4. Run the default test

### AR
 
Throws the error that can be seen in the screenshot

### Additional info
 
![image](https://user-images.githubusercontent.com/44575813/228744660-2c1d40ee-2a0e-464a-a3c8-01ceda7cdfd3.png)

## Expected result

Building the test project will be successful and will start running the test. 
Then driver will connect to the server( if there is a running server) or will throw an error that it could not connect.

## Testability

Try following the steps to reproduce and see if the Expected result happens

**Comment by ralupopa** [comment] 2023-04-05 12:34
Reproduced after adding `AltTester-Driver --version 1.8.2` nuget package

**Comment by pavel-tds** [comment] 2023-04-07 15:08
@ralupopa solution works, but it is not a fix

**Comment by RobertPoienar** [comment] 2023-04-13 14:10
As a workaround you can do the following:

1. Download the dll from: https://github.com/alttester/AltTester-Unity-SDK/blob/development/Assets/AltTester/3rdParty/websocket-sharp/netstandard2.0/altwebsocket-sharp.dll
2. Add the file in your project
3. In your csproj file add the following:
`<Reference Include="AltWebSocketSharp">
      <HintPath>altwebsocket-sharp.dll</HintPath>
    </Reference>`

HintPath - is the path where your dll is, it doesn't really need to be in your project.

![image](https://user-images.githubusercontent.com/44575813/231785584-c0da3dae-119e-4276-894a-0dbe33bbd1eb.png)

**Comment by RobertPoienar** [comment] 2023-05-03 10:04
@iulianatodoran This ticket will be tested only after the new release is deployed on Nuget. It will remain in testing until then after #1224 is merge

**Comment by iulianatodoran** [comment] 2023-05-25 06:10
### Testing environment
- IDE : VSCode
- AltTester-Driver package for AltTester Unity SDK  v.2.0.0
- AltTester Desktop v.2.0.0 (fort starting AltServer) from `development` branch (24.05.23)

### Tests performed and results
Checked that by following the steps describes in the ticket, the expected result is achieved: 
- ✅  Building the test project is successful and started running the test successfully
- ✅  The driver connected to the running server and the default test passed

### Conclusion
The purpose of this ticket was achieved: the issue is not reproducible anymore.

**Closing the ticket.**

**Closed by iulianatodoran** 2023-05-25 06:10 UTC
Labels: bug, release pro 1.0
