### ISSUE TITLE
Fix issue where the game is connected but the status message remains "Waiting for connection"

### ISSUE THREAD

**Issue by robert-altom** [alttester/AltTester-Unity-SDK#1002] opened 2022-11-29 09:21 UTC

**Comment by iulianatodoran** [comment] 2022-12-16 10:50
### Testing Environment
- SampleGame build **Standalone**, **Android 11** and  **played in Editor** - instrumented with AltTester Unity SDK from the `feature-proxy` branch in 16.12.22
- Unity v 2021.3.15f1
- AltTester Desktop v.0.7.26-Pro (from `development` branch)/ AltProxy from `master` branch

### Tests performed and results
- :heavy_check_mark: Checked that after connecting the Desktop app and then changing the Port from the game and restarting Proxy on the same port ▶️ **the game is connected back with Dekstop and the prefab message from the game is for the connected state**
- :heavy_check_mark: Checked that after connecting the Desktop app and then changing the Port from the game and restarting Proxy on a different port ▶️ **the game is not connected back with Dekstop and the prefab message from the game is for the waiting for connections state**
- :heavy_check_mark: Checked that after starting the Proxy and connecting to the game and then changing the Port from the game ▶️ **the game disconnects from Proxy and the prefab message from the game is for the waiting for connections state**
- :heavy_check_mark: Checked that after connecting the Desktop app and then changing the Host from the game ▶️ **the game disconnects from Desktop, Proxy disconnects and the prefab message from the game is for the waiting for connections state**
- :heavy_check_mark: Checked that after starting the Proxy and connecting to the game and then changing the Host from the game with a different IP than the one used by the Proxy  ▶️ **the game disconnects from Proxy and the prefab message from the game is for the waiting for connections state**
- :heavy_check_mark: Checked that after starting the Proxy and connecting to the game and then changing the Port from the game ▶️ **the game disconnects from Proxy and the prefab message from the game is for the waiting for connections state**
- :heavy_check_mark: Checked that after starting the Proxy and connecting to the game and then changing the Port from the game and also restarting Proxy with the same changed port ▶️ **the game connects back to Proxy, Desktop can be connected to the game and the prefab message from the game is for the connected state**
- :heavy_check_mark: Checked that after disconnecting the Desktop app from the game ▶️ **the game is still connected with the Proxy and the prefab message from the game is for the connected state**
- :heavy_check_mark: Checked that after starting the Proxy and connecting to the game and then trying to connect another game on the same Port ▶️ **the second game does not connect to Proxy and the prefab message from the second game is for the waiting for connections state and the first game remains connected with the message for the connected state**
- :heavy_check_mark: Checked that after the previous scenario the first game is closed ▶️ **the second game connects to the proxy and the prefab message from the second game is for the connected state**

### Conclusions
The purpose of this ticket was achieved: the issue is fixed and no other issues related to the change occured
Closing the ticket.

**Closed by iulianatodoran** 2022-12-16 10:50 UTC
Labels: bug, release pro 1.0
