### ISSUE TITLE
[BrowserStack - Intermittent] The app disconnects and reconnects quickly to the AltServer

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1521] opened 2024-03-06 15:26 UTC
## Steps to reproduce
 
1. Open the AltTesterDesktop 
2. Open the instrumented game in BrowserStack
3. Connect the instrumented game to the Built-in Server
4. Wait until the game disconnects and reconnects to the server
### AR
 
The app disconnects and reconnects quickly to the AltServer
### Additional info
 
***Setup:***
- Windows 10
- AltTesterDesktop made with dev from `01.03.2024`
- IPA app hosted on BrowserStack (`AppLive`)  instrumented with SDK from `01.03.2024`
### ER
 
The game shouldn't disconnect and reconnect to the server without user intervention.

**Comment by iulianatodoran** [comment] 2024-12-10 14:06
I tried two times and could not reproduce this disconnection/ reconnection (as checked in the server logs) for extended periods (15 and 30-minute sessions). also, the issue was not reported in the recent months. 

Considering this, I will close this ticket. If the problem arises again, a new ticket should be opened.

**Closed by iulianatodoran** 2024-12-10 14:06 UTC
Labels: bug
