### ISSUE TITLE
Remove input visualizer and modify contributing page in documentation

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1377] opened 2023-08-31 05:27 UTC
Remove everything that has to do with input visualizer

## Testability

Documentation changes is required

**Comment by iulianatodoran** [comment] 2023-09-01 12:01
### Testing environment
- OS: Windows 10, MacOS Big Sur 11.7.7
- Unity v 2021.3.16f1
- AltTester Unity SDK v 2.0.2 
- Staging documentation for AltTester Unity SDK

### Tests perform and results
- ✅ Checked in the AltTester Unity SDK repo that there is no mention of `Input Visualizer`
- ✅ Checked in the AltTester Editor window in Unity that the `Input Visualizer` option is not present anymore in the `Build Settings `section
- ✅ Checked that I am able to play in Editor the instrumented build (with or without `Keep ALTTESTER symbol defined` checked) and connect successfully to the AltServer
- ✅ Checked that I am able to create and run an instrumented build and connect successfully to the AltServer
- ✅ Checked that the main functionalities in the AltTester Editor work as expected 
  - ❌ found an [issue](#1381) with the `Show popup` option malfunction (present before this fix)
- ✅ Checked that there are no UI issues in the AltTester Editor window
  - ❌ found an [issue](#1384 ) with the horizontal splitter between the `Tests list` and `Build Settings` sections  (present before this fix)
- ✅ Checked in the Staging docs that the Input Visualizer mentions are removed and also that the screenshots that used to contain it are updated accordingly
  - ❌ In the _Overview_ section there was a mention left in the `Key features` list but it was fixed in #1380  

### Issues found during testing
- #1381 
- #1384

### Conclusions
- For the above-mentioned issues opened different tickets because they are not related to the fix from this ticket
- The expected behaviors occur for this ticket

**Closing the ticket**.

**Closed** 2023-10-12 07:04 UTC
Labels: bug, release pro 2.1

**Comment by MihaiCuc98** [comment] 2023-10-12 09:28
This issue was reopened because there were some errors when only the new input system was activated in the PlayerSettings.

**Comment by MihaiCuc98** [comment] 2023-10-12 12:40
The testing session is done.
### Setup:
- Windows 10
- Unity2021.3.19f
- Roll-a-boll game (only NIS Activated) instrumented with the latest SDK from dev branch (12.10.2023 - 11:00)
- Trashcat game (only OIS Activated) instrumented with the latest SDK from dev branch (12.10.2023 - 11:00)

### What was checked:
✔ Checked if there is no AlTester Input Visualizer checkbox or any reference to the input visualizer in AltTester Editor.
✔ Checked if no error is triggered when the `Play in editor` is used.
- ❌check the [comment](https://github.com/alttester/AltTester-Unity-SDK/issues/1393#issuecomment-1759317279 -> the problem is caused by that ticket)

✔ Checked if no error is triggered when a build is made (checked with standalone and Android builds)
- ❌check the [comment](https://github.com/alttester/AltTester-Unity-SDK/issues/1393#issuecomment-1759317279 -> the problem is caused by that ticket)

✔Checked if no input visualizer is displayed in the instrumented game when:
- the game is connected to the desktop and some click/tap/hold/swipe operations are made in the screenshot area (checked if no input visualizer is displayed in the screenshot area as well)
- some tests (click/tap/swipe/hold) are run on the game 

Considering this information, I will move this ticket into `done`.
