### ISSUE TITLE
When switching platform in AltTesterEditor the UnityEditor.EditorUserBuildSettings.activeBuildTarget is not changed

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1076] opened 2023-01-26 09:21 UTC
## Steps to reproduce
 

1. Check what platform is currently selected from build settings
2. Switch to a different platform( in AltTesterEditorWindow(ATEW))
3. Check to see in build setting if the platform you switched in ATEW is selected

## Actual result

Platform is still the one selected before switching

## Expected result
The new platform is the one selected

**Comment by iulianatodoran** [comment] 2023-01-31 15:16
### Testing environment
- Unity v `2021.3.16f1` (Windows 11/MacOs Big Sur 11.7.2)
- AltTester Unity SDK from `development` branch from 31.01.23

### Tests performed and results
- ✅ Checked in Unity in the _Altester Editor_ window that by following the steps described in the ticket the expected result is achieved: the new platform is the one selected
- ✅ Checked that by switching again to a different platform in _Build Settings_ (unity native) the last chosen platform is selected
- ✅ Checked in the _Altester Editor_ window that all the other functionalities still work as expected and the correct settings are displayed for each selected platform
- ✅ Checked in Unity in the _Altester Editor_ window that there are no UI/Layout related issues after the tix

### Conclusions
- The purpose of this ticket was achieved: the issue is fixed

**Closing the ticket**.

**Comment by iulianatodoran** [comment] 2023-02-01 09:55
Reopening for an issue found by @RobertPoienar ⤵️ 

### Issue
- when first importing the AltTester package in Unity, before opening the `AltTester Editor` window, the platform selected in _Build Settings_ from Unity is switched to `Android` in the `AltTester Editor` window on opening

### Testability steps
1. Close the `AltTester Editor` window is it is opened
2. If the AltTester is already inside the project, delete the `AltTesterEditorSettings.asset` file from `Assets/AltTester/Editor/` 
3. Open the `AltTester Editor` window and check the selected platform

**Closed** 2023-02-01 11:54 UTC
Labels: bug, alttester editor, 1.8.2 HotFix

**Comment by iulianatodoran** [comment] 2023-02-01 12:24
### Re-testing conclusions
- Re-tested after the last fix and the issue is fixed. Also, following the steps from the initial ticket, the expected behavior still occurs.
- Also the C# syntax issue found when project was opened in unity 2020 was also fixed and there are no errors in the Unity console
- No other issues were found. 

**Closing the ticket.**
