### ISSUE TITLE
[Connection] Another app with "app_name" error in the instrumented game pop-up when the Restart button is pressed for 2 or more times

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1266] opened 2023-05-24 08:48 UTC
## Steps to reproduce
 
1. Open the desktop app
2. Open the instrumented game (make sure that the instrumented game is not automatically connected to the server)
3. Configure the connection parameters
4. Press the Restart button of the instrumented pop-up twice or more
## Actual result

 
The `another app with "app_name" app_name` error is triggered into the instrumented pop-up, even if there is just 1 game that tries to connect to the server
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/113912901/6735bf2c-a822-431f-95f9-6ed85b09c607)

## Expected result

There should be no errors when the Restart button of the instrumented pop-up is pressed two or more times.

**Comment by sandraaltom** [comment] 2023-09-21 08:46
Triaged Week #38, 2023. 
Not prioritised for next releases.

**Comment by iulianatodoran** [comment] 2024-04-22 09:28
The issue is not reproducible anymore using instrumented builds with AltTester Unity SDK v `2.1.0` as the `Restart` button cannot be pressed multiple times after changing the connection data

Considering the above, **I will close this ticket and move it to `Done`.**

**Closed by iulianatodoran** 2024-04-22 09:28 UTC
Labels: bug, triaged
