### ISSUE TITLE
[Connection-INTERMITENT] The message from the instrumented game pop-up contains a Waiting for driver sub-message when the instrumented game is connected to the Desktop

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1267] opened 2023-05-24 09:24 UTC
## Steps to reproduce
 
1. Open the Desktop app
2. Open the instrumented game and connect it to the Desktop app
3. Restart the server then press the connect button from the Desktop connection panel
## Actual result

 
Sometimes, the message from the instrumented game says that the app (game) is not connected to a driver (Waiting for Driver to connect ), even if it is actually connected to the desktop:
<img width="500" alt="image (22)" src="https://github.com/alttester/AltTester-Unity-SDK/assets/113912901/6c787674-da96-473c-9bc7-46c6083a9414">

 ### Additional info
 

## Expected result

 
The message from the instrumented game should contain the `Driver connected` sub-message when the Driver (Desktop) is connected to the app (game)
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/113912901/e6676f42-fd81-4382-9eac-2d90559a5fb4)

**Comment by MihaiCuc98** [comment] 2023-05-24 09:25
@sandraaltom I will put this into `ToDo` but with no release pro 1.0 label

**Comment by sandraaltom** [comment] 2023-11-10 09:54
Triaged Week no. 45. Not prioritised for next releases. 
@MihaiCuc98 please re-test this after we have the concurrency and web socket stories implemented.

**Comment by iulianatodoran** [comment] 2024-04-22 09:21
✅ Checked multiple times using the SampleGame and TrashCat instrumented builds with AltTester Unity SDK v `2.1.0` and AltTester Desktop v `2.1.0` and could not reproduce the issue.
- could also not reproduce with variations for the disconnecting method of the instrumented app from the Desktop 

Considering the above, **I will close this ticket and move it to `Done`.**

**Closed by iulianatodoran** 2024-04-22 09:21 UTC
Labels: bug, triaged
